tier4/caret_trace

include/caret_trace/tracing_controller.hpp
src/hooked_trace_points.cpp
src/ros_trace_points.cpp
src/tracing_controller.cpp

特に/clockトピックの初期化トレースポイントが、Autowareを立ち上げた際に突発的に記録され、
その際にトレース結果のロストが発生していた。
CARETは初期化時に実行される関数からトピック名などとの紐付けに使うため、
初期化時のロストは測定を出来なくしてしまう。
元々/clockトピックのsubscription コールバックのstart/endといったランタイムのトレースポイントをフィルタリングするための機能であったが、
上記の問題が上がったため、初期化時のトレースポイントもフィルタリング対象に追加する。
ただし、初期化時のトレースポイントは関数の実行順序からノード名・トピック名と紐付けられない関数もある。
取り急ぎ、ノード名・トピック名と簡単に紐付けられる初期化関数のトレースフィルタリング適用をした。

 初期化時のトレースポイントにトレースフィルタリングの適用

---

.github/sync-files.yaml

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>
This PR modify sync origin to caret_common.
This PR is needed to merge https://github.com/tier4/CARET_trace/pull/45.
Note that cpplint and clang-format are to be removed!
Changes: (differences between [current .pre-commit-config.yaml](https://github.com/tier4/CARET_trace/blob/main/.pre-commit-config.yaml) and [caret_common's pre-commit-config.yaml](https://github.com/tier4/caret_common/blob/main/.pre-commit-config.yaml))
- hadolint-py is removed (not related for this repo because hadolint-py is tool for dockerfile)
- isort is added (not related for this repo because isort is tool for python)
- black is added (not related for this repo because black is tool for python)
Major changes are not related for this repo, but sync-files …

chore(sync-files): modify sync origin to caret_common

---

.github/sync-files.yaml

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>
This PR fixes conflicts between sync-files and dependabot
- https://github.com/tier4/CARET_trace/pull/71
- https://github.com/tier4/CARET_trace/pull/67

chore(github action): ignore version for tj-actions/changed-files in sync files

---

.github/workflows/build-and-test-differential-self-hosted.yaml
.github/workflows/build-and-test-differential.yaml
.github/workflows/build-and-test-self-hosted.yaml
.github/workflows/build-and-test.yaml
.github/workflows/check-build-depends.yaml

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>
This PR disalbes test related to galactic.
galactic tests are not necessory because [caret.repos](https://github.com/tier4/caret/blob/galactic/caret.repos) doesn't use main branch for galactic version.
#68 tests fail in  `build-and-test-differential (galactic)` because it uses lttng2.13 features.

chore(github action): disable galactic tests

---

.github/sync-files.yaml

Reverts tier4/CARET_trace#78
sync_file fails.
https://github.com/tier4/CARET_trace/actions/runs/3512256621/jobs/5883782026#step:12:282

fix: revert "ci: stop sync until autoware_common stops Galactic support."

---

CARET_trace/src/clock_recorder.cpp

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>
This PR adds warning log in clock_recorder node when /clock is not published.
To reproduce:
```
mkdir -p ~/ros2_ws_test/src
cd ~/ros2_ws_test/src
git clone https://github.com/hsgwa/CARET_trace.git feat_add_warn_if_simtime_is_unable
git clone https://github.com/hsgwa/clock_publisher.git
cd ~/ros2_ws_test
. /opt/ros/humble/setup.bash
colcon build
. ./install/setup.bash
ros2 run caret_trace clock_recorder
> clock_recorder started to record sim time.
> Failed to get simtime correctly. /clock topic may  note have been published.
. ./install/setup.bash
ros2 run clock_publisher publisher
```

feat: add warning when /clock is not published

---

CARET_trace/include/caret_trace/tracing_controller.hpp
CARET_trace/src/ros_trace_points.cpp
CARET_trace/src/tracing_controller.cpp

CARET adds trace points by forking some repositories, such as rclcpp, ros2-tracing.
It was therefore essential to rebuild the target application in order to measure and evaluate it.
In this PR, the tracepoint `rmw_take` added to humble is changed to be used instead of the tracepoint `dispatch_subscription_callback` added by the fork, which was necessary for the evaluation of inter-process communication.
This change allows the system to be evaluated using inter-process communication without rebuilding the target application.
- https://github.com/tier4/CARET_analyze/pull/296

feat: support rmw_take tracepoint

---

CARET_trace/src/ros_trace_points.cpp

Some of the processes started with python3 had a process that issued rcl_timer_init() not associated with a node in a short cycle.
As a result, the information acquired by CARET_trace increases with the passage of time, and a phenomenon occurs in which it takes time to complete measurement.
For this reason, restrict rcl_timer_init() to be excluded when invoked by the python3 command.
(memo)Currently, measurement via python3 (rclpy) is not supported.
https://tier4.atlassian.net/browse/RT2-591

feat: ignore rcl_timer_init() from ros2 launch command

---

CARET_trace/src/ros_trace_points.cpp

Some parts of the current CARET define their own trace points. For future development, information that is no longer needed (e.g. message_timestamp in rclcpp_publish) will be removed and the function signatures will be modified to match.

feat: change publish trace point definition

---

CARET_trace/src/ros_trace_points.cpp

Enable the `dispatch_subscription_callback` trace point for  supporting `Rclcpp::GenericSubscription`.
- https://github.com/tier4/rclcpp/pull/7

feat: add dispatch subscription for generic_subscirption

---

CARET_trace/src/hooked_trace_points.cpp

Add tracepoints for communication of serialized data using CycloneDDS.
This PR is one of a series of PRs that provide recording of applications using `rclcpp::GenericSubscription`, `rclcpp::GenericPublisher`.
- https://github.com/tier4/caret_trace/pull/220
- https://github.com/tier4/rclcpp/pull/7

feat(hooked_trace_point.cpp): add tracepoint to cyclonedds for serialized_publish

---

CARET_trace/src/tracing_controller.cpp

Fixed a problem in which the filter function did not work due to a change from the address at initialization during application execution. This problem occurs when using `RCLCPP_INFO`, etc.
[Tier4 INTERNAL LINK](https://tier4.atlassian.net/browse/RT2-933)

feat: filter unregistered pubsiher_handle

---

CARET_trace/include/caret_trace/tracing_controller.hpp
CARET_trace/src/hooked_trace_points.cpp
CARET_trace/src/ros_trace_points.cpp
CARET_trace/src/trace_node.cpp
CARET_trace/src/tracing_controller.cpp

Traces of processes listed in the environment variable CARET_IGNORE_PROCESSES are filtered.
[https://tier4.atlassian.net/browse/RT2-1382](https://tier4.atlassian.net/browse/RT2-1382)

feat: add ignore processes filter

---

CARET_trace/src/hooked_trace_points.cpp

special duplicate check removal using static variables
https://tier4.atlassian.net/browse/RT2-1529

feat: special duplicate check removal using static variables

---

CARET_trace/include/caret_trace/tracing_controller.hpp
CARET_trace/src/ros_trace_points.cpp
CARET_trace/src/tracing_controller.cpp

Segmentation failure occurred at autoware pandar_node_container.
From the backtrace, it was confirmed that it occurs within TracingController::add_allowed_messages() in caret_trace.
[https://tier4.atlassian.net/browse/RT2-1592](https://tier4.atlassian.net/browse/RT2-1592)
After adding an exclusive lock to add_allowed_messages(), the segmentation fault no longer occurred, but the cause was unknown.
Examination revealed that ‘writes’ were mixed in the shared lock and that the segmentation fault was caused by corruption of the map data due to thread contention.
The shared and exclusive locks were reviewed with a focus on TracingController and the following modifications were made.
-  Move add_allowed_messages() from is_allowed_publisher_handle_and_add_message() to …

fix: segmentation fault due to race condition.

---

CARET_trace/src/hooked_trace_points.cpp

The dds_bind_addr_to_stamp output of **generic_publish()** is controlled as follows.
- Before jazzy: Always output.
- After jazzy: Those associated with rcl_publish are subject to the filter.
[https://tier4.atlassian.net/browse/RT2-1640](url)

fix: controlling the dds_bind_addr_to_stamp output of generic_publish()

---

CARET_trace/include/caret_trace/data_container.hpp
CARET_trace/src/ros_trace_points.cpp

fixed incorrect arguments in rclcpp_service_callback_added
https://tier4.atlassian.net/browse/RT2-1614

fix: fixed incorrect arguments in rclcpp_service_callback_added

---

CARET_trace/include/caret_trace/tracing_controller.hpp

The is_allowed_XXX(XXX) system shall be set to XXX as in Check if trace point is an enabled XXX as specified in the argument.
[https://tier4.atlassian.net/browse/RT2-1524](https://tier4.atlassian.net/browse/RT2-1524)

fix: comments for doxygen

---

.github/workflows/cppcheck-all-files.yaml

Remove the pull-request trriger in cppcheck-all-files.
[https://tier4.atlassian.net/browse/RT2-1667](https://tier4.atlassian.net/browse/RT2-1667)

fix: remove pull-request trriger in cppcheck-all-files

---

CARET_trace/include/caret_trace/data_container.hpp
CARET_trace/include/caret_trace/trace_node.hpp
CARET_trace/src/clock.cpp
CARET_trace/src/data_container.cpp
CARET_trace/src/hooked_trace_points.cpp
CARET_trace/src/ros_trace_points.cpp
CARET_trace/test/include/test/mock.hpp
CARET_trace/test/test_data_container.cpp
CARET_trace/test/test_hashable_keys.cpp

Explicitly include cstdint for gcc13.
[https://tier4.atlassian.net/browse/RT2-1669](https://tier4.atlassian.net/browse/RT2-1669)
Compiling with gcc13 does not result in an error, but given that changes in gcc13 have changed the header dependencies of the C++ standard library, this behaviour may change in future versions, so cstdint was added explicitly on this occasion.

fix: explicitly include cstdint for gcc13

---

CARET_trace/src/clock_recorder.cpp

Add a warning indicating sim_time reversal detection.
MSG: Detect sim_time decreased: <previous time> -> <current time> at [<count of wall timer timeout>]
[https://tier4.atlassian.net/browse/RT2-2003](https://tier4.atlassian.net/browse/RT2-2003)

chore: add warning indicating sim_time reversal detection

---

CARET_trace/CMakeLists.txt
CARET_trace/include/caret_trace/data_container.hpp
CARET_trace/include/caret_trace/tp.h
CARET_trace/src/data_container.cpp
CARET_trace/src/hooked_trace_points.cpp
CARET_trace/src/ros_trace_points.cpp
CARET_trace/src/trace_node.cpp
CARET_trace/test/test_data_container.cpp
CARET_trace/test/test_scenario.cpp

jazzy support
https://tier4.atlassian.net/browse/RT2-1803

feat: jazzy support
